---
- name: Distribute Kubernetes binary file
  copy: 
    src: '/usr/local/bin/{{ item }}'
    dest: /usr/local/bin/
    mode: 0744
    owner: root
    group: root
  with_items:
    - kubelet
    - kubectl
    - kube-proxy