---
- name: Distribute Kubernetes binary file
  copy: 
    src: '/usr/local/bin/{{ item }}'
    dest: /usr/local/bin/
    mode: 0744
    owner: root
    group: root
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-proxy
    - kube-scheduler
    - kubectl
    - kubelet