
# Ingress Nginx
- name: Ingress Controller Nginx step 1/3
  template:
    src: '{{ item }}'
    dest: /usr/local/src/kubernetes/ingress-nginx/
  with_items:
    - ingressnginx/ingress-controller-cm.yml
    - ingressnginx/ingress-controller-rbac.yml
    - ingressnginx/ingress-controller-sa.yml
    - ingressnginx/ingress-controller-svc.yml
    - ingressnginx/ingress-controller.yml
    - ingressnginx/ingress-controller-ns.yml

- name: Ingress Controller Nginx step 2/3
  command: kubectl apply -f /usr/local/src/kubernetes/ingress-nginx/ingress-controller-ns.yml
  when: IngressController == "nginx"
  run_once: true

- name: Ingress Controller Nginx step 3/3
  command: kubectl apply -f /usr/local/src/kubernetes/ingress-nginx
  run_once: true
  when: IngressController == "nginx"

- name: Ingress Controller Traefik step 1/2
  template:
    src: '{{ item }}'
    dest: /usr/local/src/kubernetes/Traefik/
  with_items:
    - Traefik/1.Namespace.yaml
    - Traefik/2.ClusterRole.yaml
    - Traefik/3.ServiceAccount.yaml
    - Traefik/4.DaemonSet.yaml
    - Traefik/5.Service.yaml
    - Traefik/6.Ingress.yaml

- name: Ingress Controller Traefik step 2/2
  command: kubectl apply -f /usr/local/src/kubernetes/Traefik/
  run_once: true
  when: IngressController == "traefik"