---
# Metrics Server
- name: Metrics Server step 1/3
  file: 
    path: /usr/local/src/kubernetes/metricsserver
    state: directory 
    mode: 0655

- name: Metrics Server step 2/3
  template:
    src: metricsserver/metrics-server.yml
    dest: /usr/local/src/kubernetes/metricsserver

- name: Metrics Server step 3/3
  command: kubectl apply -f /usr/local/src/kubernetes/metricsserver/metrics-server.yml
  run_once: true
  when: MetricsServer == True