---
# This Playbook Install Kubernetes Addon

# flannel
- name: Kubernetes Addon NFS stp 1/3
  package:
    name: nfs-common
  when: NFS == True

- name: Kubernetes Addon NFS stp 2/3
  template:
    src: '{{ item }}'
    dest: /usr/local/src/kubernetes/nfs/
  with_items:
    - nfs/class.yaml
    - nfs/deployment.yaml
    - nfs/rbac.yaml

- name: Kubernetes Addon NFS stp 3/3
  command: kubectl apply -f /usr/local/src/kubernetes/nfs/
  run_once: true
  when: NFS == True